name: example
description: Example app for smart_refresh_token
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  smart_refresh_token:
    path: ..
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4

flutter:
  uses-material-design: true
