name: example
description: Example app for smart_refresh_token
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  smart_refresh_token:
    path: ..

flutter:
  uses-material-design: true
